### ISSUE TITLE
some questions about your work :)

### ISSUE THREAD

**Issue by XiaohanChen97** [rampasek/DrVAE#2]
Hi, Prof. Rampasek:
    I'm a graduate student of Tongji University in Shanghai, China. I major in Bioinformatics.
    Recently I read your article about this work in github, which makes a really positive contribution to my research work. This is really a nice work. But I got some trouble when I try to implement the data preprocessing, which also important for my current research work.
    So could you please send me a copy of the source codes of data preprocessing if possible? I would be very appreciated if you can help me. :)

**Comment by rampasek** [comment]
Hello,
I attach the set of my R scripts that I used to collect and process the dataset. Hope it helps!
[drvae-Rscripts.zip](https://github.com/rampasek/DrVAE/files/3969976/drvae-Rscripts.zip)

**Comment by XiaohanChen97** [comment]
That really helps me a lot. Thank you so much.
