### ISSUE TITLE
About the data file

### ISSUE THREAD

**Issue by juychen** [rampasek/DrVAE#3]
Hi,

How do you obtain the L1000 data file?
Is it download via the PharmacoGx package or from the GEO website?

Regards,
Junyi

**Comment by rampasek** [comment]
Hi Junyi,

I downloaded the L1000 dataset via PharmacoGx. Here is a direct link to the PSet file: https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/L1000_compounds.RData

Best,
Ladislav

**Comment by hmkim** [comment]
@rampasek 
Can I recognize the version of PharmacoGx (e..g sessionInfo() in R) ?

**Comment by rampasek** [comment]
Hi @hmkim,

Unfortunately I don't have access to the computer(s) I used for this project anymore. The PharmacoGx version I used was from 2018, it was certainly some 1.X version, may be 1.6?

In case it helps, in another answer I shared my R data processing scripts:
https://github.com/rampasek/DrVAE/issues/2#issuecomment-566229366

Best,
Ladislav

**Comment by hmkim** [comment]
Hi @rampasek ,

Thank you for your comment.
I also guess the version fo PharmacoGx in your case. I'll try the 1.X version of PharamcoGx.

I already check it. [#2 (comment)](https://github.com/rampasek/DrVAE/issues/2#issuecomment-566229366) 

Best,
Hyunmin
